name: Generate JSON and Publish Artifact

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  generate-json:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: python barrinha_data.py

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-json
        path: barrinha.json  
