name: Generate JSON and Publish Artifact

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python barrinha_data.py
      
      - name: Commit report
        run: |
          git config --global user.name 'vargas'
          git config --global user.email 'vargacypher@users.noreply.github.com'
          git commit add ./barrinha.json
          git commit -m "Automated report"
          git push
