name: Generate JSON and Publish Artifact

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour
  workflow_dispatch:
  

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: python barrinha_data.py

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-json
        path: barrinha.json  
